project_id = "gkciojbfkjlkvjerbona"

[functions.google-sheets-cms]
verify_jwt = false

[functions.contact-form]
verify_jwt = false

[functions.membership-form]
verify_jwt = false

[functions.purplbook-directory]
verify_jwt = false

[functions.policy-library]
verify_jwt = false

[functions.utility-rate-tracker]
verify_jwt = false

[functions.mailchimp-subscribe]
verify_jwt = false 
 
[functions.michigan-essential-services]
verify_jwt = false
